version: '3'
services:
  mariadb:
    build: ./src
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: example
      #TZ: Asia/Tokyo
    volumes:
      - ./data:/var/lib/mysql
      - ./src/config/my.cnf:/etc/mysql/my.cnf
    hostname: mariadb
    ports:
      - "3306:3306"
    command: mysqld
    restart: unless-stopped