# example of docker-compose.yml
version: '3'
services:
  mariadb:
    build: ./src
    environment:
      MARIADB_ROOT_PASSWORD: pass
      MARIADB_USER: mariadb
      MARIADB_PASSWORD: pass
      MARIADB_DATABASE: example
      #TZ: Asia/Tokyo
    volumes:
      - ./data:/var/lib/mysql
      - ./src/config/my.cnf:/etc/mysql/my.cnf
    hostname: mariadb
    ports:
      - "3306:3306"
    # NOTE: without upgrade command
    # command: ["mariadbd", "--character-set-server=utf8mb4"]
    # NOTE: with upgrade command.
    command: >
        mariadbd --character-set-server=utf8mb4 --general_log=1 --general_log_file=/var/log/mysql/general.log &&
        mariadb-upgrade
    restart: unless-stopped